export const FETCH_CATALOGUE_LOADING = 'FETCH_CATALOGUE_LOADING'
export const FETCH_CATALOGUE_SUCCESS = 'FETCH_CATALOGUE_SUCCESS'
export const FETCH_CATALOGUE_FAIL = 'FETCH_CATALOGUE_FAIL'

export const FETCH_MEDIA_DETAILS_LOADING = 'FETCH_MEDIA_DETAILS_LOADING'
export const FETCH_MEDIA_DETAILS_SUCCESS = 'FETCH_MEDIA_DETAILS_SUCCESS'
export const FETCH_MEDIA_DETAILS_FAIL = 'FETCH_MEDIA_DETAILS_FAIL'